<?php
/**
 * @user: thanatos <thanatos915@163.com>
 */

namespace common\components\validators;


use yii\validators\Validator;

class PathValidator extends Validator
{
    public $message;
    public $pattern = "/^\S+\/\w+\/\d+\/d+\/\.\d{3-10}/";

    public function init()
    {
        if ($this->message === null) {
            $this->message = '路径格式不正确';
        }
        parent::init(); // TODO: Change the autogenerated stub
    }

    protected function validateValue($value)
    {
        $valid = preg_match($this->pattern, $value);
        return $valid ? null : [$this->message, []];
    }
}